### ISSUE TITLE
NoMethodError: undefined method `helper' for ActionController::API:Class

### ISSUE THREAD

**Issue by ryanstuhl805** [basecamp/marginalia#94]
When I try to install the gem as is, I get the error in the issue title. Is anyone else getting the same error? 

I've looked into this error and it sounds like instead of using `ActiveSupport.on_load :action_controller do` on `lib/marginalia/railtie.rb:13` it should be using `ActiveSupport.on_load :action_controller_base do`. Can someone confirm this?

**Comment by arthurnn** [comment]
Which Rails version are you using?

**Comment by ryanstuhl805** [comment]
I'm running rails 5.2.3 and ruby 2.3.7. I found [this PR](https://github.com/opoloo/lines-engine/pull/25/commits/173d32672f995a231debaf91fff81e9c3686210d) on a different Gem referencing the same error message I encountered which is why I think the action_controller needs to be action_controller_base. Perhaps this is a >= Rails 5 compatibility issue?

**Comment by sj26** [comment]
Marginalia doesn't include any references to `helper`. The [test suite](https://github.com/basecamp/marginalia/actions/workflows/ci.yml) confirms compatibility with Rails 5.2 and 6.0.

Perhaps this issue is stale? Please reopen if you're still experiencing this error, and please include a full backtrace and relevant versions.
